  language: python
  python:
    - 3.6
  install:
    - pip install -r ./.travis/deps.txt
  script:
    - if [[ $TRAVIS_EVENT_TYPE == 'push' ]]; then python ./.travis/publish.py; fi
    - if [[ $TRAVIS_EVENT_TYPE == 'pull_request' ]]; then python ./.travis/test.py; fi
